### PR TITLE
Use Kibana Saved Objects API

### LINKED ISSUE #318: upload-kibana-objects does not work with Kibana v6
Hi,

I have seen the know issues note in releases tab, but is there any bug report tracking the issue?

Additionally, is there any more specific information about what has to be changed? I have seen the info: https://www.elastic.co/guide/en/elasticsearch/reference/6.7/removal-of-types.html, but I don't really see why it affects all imported objects as documents seem to be added to the without an error to ".kibana" index and there is only one type ("doc") in the json?

### PR DESCRIPTION
**Pull request by Infra-Red**
1. Update saved objects format to support Kibana API.
1. Add a task to import saved objects to Kibana API.

Please first merge https://github.com/cloudfoundry-community/logsearch-boshrelease/pull/140

Fixes https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/issues/318

### CODE REVIEW

**Review by axelaris — APPROVED** [review]
Cool!

**Comment by vetin4ri** [comment]
@Infra-Red Thats great you have fixed the problem, but when I look at the change:

https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/319/commits/8642c7f8584377ed6a692e75063b74b771397380

it seems like instead of using `elastichserch.host` you are using now `CF_SYSTEM_DOMAIN`. This means the job cannot be used anymore when Kibana is not installed as a CF app. Is this required from now on, or there was another reason for the change?

**Comment by Infra-Red** [comment]
Hey @vetin4ri! Is your Kibana instance accessible via CF route? Usually it’s should be available at `logs.CF_SYSTEM_DOMAIN`.

**Comment by vetin4ri** [comment]
Hi @Infra-Red, not really, we are using a setup where ELK is not associated with specific CF installation, but can handle logs deployments, including Kubernetes. It is not accessible via CF route nor installed on CF, but also in a separate network.  

We were using upload-kibana-objects as it was loosely coupled with other jobs and could be easily used on its own.

**Pull request merged**
