### PR TITLE
Hide build status

### PR DESCRIPTION
**Pull request by kinjelom**
https://concourse.altoros.com/ is not working

### CODE REVIEW

**Comment by Infra-Red** [comment]
@axelaris @poligraph Do you know why Concourse integration stopped working?

**Comment by kinjelom** [comment]
Looks like altoros.com stopped hosting https://concourse.altoros.com ?

**Comment by Infra-Red** [comment]
@wildloop Let’s keep PR opened for sometime until someone from Altoros (I expect @axelaris or @poligraph) will reply.

**Comment by poligraph** [comment]
@wildloop @Infra-Red we moved https://concourse.altoros.com to https://ci.altoros.com about year ago.

**Comment by kinjelom** [comment]
@poligraph Is there `/api/v1/teams/Logsearch/pipelines/logsearch-for-cloudfoundry-pr`?
How to change the build status links:
- https://concourse.altoros.com/api/v1/teams/Logsearch/pipelines/logsearch-for-cloudfoundry-pr/jobs/pr%20tests/badge
- https://concourse.altoros.com/teams/Logsearch/pipelines/logsearch-for-cloudfoundry-pr

**Comment by Infra-Red** [comment]
@wildloop I think the pipeline is not presented in new Altoros Concourse instance. Let's remove badge for now and later we can recreate the unit tests in some other public system (smth like Circle CI).

**Review by Infra-Red — APPROVED** [review]

**Pull request merged**
