### PR TITLE
Update l4cf to work with elk 5

### PR DESCRIPTION
**Pull request by Isaacjcollier**
Signed-off-by: Isaac Collier <icolp@allstate.com>

### CODE REVIEW

**Comment by Infra-Red** [comment]
Hi @bonzofenix @Isaacjcollier 
I've deployed this patch and observed numerous messages in parser logs:
```
[2017-03-27T12:46:53,326][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logs-platform-2017.03.27", :_type=>"vcap", :_routing=>nil}, 2017-03-27T12:46:18.218Z %{host} %{message}], :response=>{"index"=>{"_index"=>"logs-platform-2017.03.27", "_type"=>"vcap", "_id"=>"AVsPzgnEttOlov0HowSQ", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to find type parsed [multi_field] for [component]"}}}}
```

**Comment by Infra-Red** [comment]
`multi-field` was completely removed in Elasticsearch 5. PR https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/242 fixes this issue.

**Comment by Infra-Red** [comment]
@Isaacjcollier @bonzofenix  This PR ready to ship after merging https://github.com/cloudfoundry-community/logsearch-for-cloudfoundry/pull/242. Can you resolve and rebase, please?

**Comment by bonzofenix** [comment]
@Infra-Red merged TY!

**Comment by bonzofenix** [comment]
@Infra-Red sorry about that the Test suite is green now.

**Comment by Infra-Red** [comment]
@Isaacjcollier @bonzofenix Thanks for contribution!

**Pull request merged**
