### PR TITLE
Fix index mappings for ELK 7

### LINKED ISSUE #345: Dashboards and Visualizations don't work in a fresh install of 211.0.1
Did a fresh deployment of 211.0.1 and most (if not all) dashboards and visualizations don't work and return errors:
``` Error in visualisation
[esaggs] > "field" is a required parameter
```
and
```
Saved "field" parameter is now invalid. Please select a new field.
```

Digging a little bit it looks like the removal of the index mappings caused this. When checking the mappings I have as an example these two:
- @cf.app of type string with searchable true
- @cf.app.keywork of type string with searchable true and aggregatable true

This is like that for all the string fields. Prior to 211.0.1 the included mappings didn't include any of the .keyword fields. Since the visualizations still reference @cf.app for example they don't work, but do if @cf.app.keyword is used.

### PR DESCRIPTION
**Pull request by mymasse**
Also fixes #345

### CODE REVIEW

**Comment by mymasse** [comment]
Can somebody test this before merging. I'm not setup at all to test this.

**Comment by TheMoves** [comment]
Will test this weekend in my lab environment.

**Comment by TheMoves** [comment]
Hoping to test the changes today...

**Comment by TheMoves** [comment]
Looks good to me, I was able to browse logs after generating traffic to some simple apps and running a few errands on CF, also the Upload Kibana Objects worked too:
```
bbl-state$ bosh task --result 21223 | grep Success | jq .stderr  | sed 's/\\n/\n/g' | grep -v Insecure
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-Logs.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Overview.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-Haproxy.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-UAA-Audit.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Metrics.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-Overview.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Location.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Logs.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/Platform-Errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/dashboard/App-Performance.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-links.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-logs-count-in-timeline.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-names.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-response-times-(50th-and-95th-first-10-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-APP-logs-count-by-level-(top-5-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-Haproxy-request-status-codes-in-timeline.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-APP-logs-count-by-level.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-logs-by-source-job-(top-5).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-UAA-Audit-event-locations.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-components-with-errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-links.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-components.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-UAA-Audit-event-types.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-request-count-by-timezone-(top-5).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-logs-by-component-(top-5).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-Haproxy-request-time-duration-(50th-95th-99th-top-5).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-traffic-by-response_time_ms-(first-10-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-Haproxy-requests-(top-10).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-APP-logs-count-(top-10-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-logs-count-by-source-type-(APP-or-cf-top-5-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-UAA-Audit-events-by-type.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-Haproxy-request-time-duration.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-logs-count-(top-10-components).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-METRIC-CPU-usage.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-errors-count-in-timeline-(top-5-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-logs-count-by-level.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-request-count-(top-10-apps).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-METRIC-memory-usage.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-apps-with-errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-requests-map.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-APP-logs-count-in-timeline.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-errors-count-in-timeline.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-RTR-response-times.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-METRIC-disk-usage.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/Platform-errors-count-by-source-component-(top-5).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/visualization/App-logs-by-source-type-(top-10).json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-all.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-http.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-rtr-long-response.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-counter.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-container-metric.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-all-errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-all-overview.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-all-errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-haproxy-long-response.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-rtr.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-logs.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-uaa-audit.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-value-metric.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-all-messages.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-haproxy.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/app-logs-errors.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-all-overview.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/search/platform-all.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/index-pattern/logs-app*.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/index-pattern/logs-platform*.json Uploaded Successfully
INFO:root:Object /var/vcap/jobs/upload-kibana-objects/kibana-objects/index-pattern/logs-*.json Uploaded Successfully
INFO:root:Successfully Set logs-app* as Default Index
```

**Comment by TheMoves** [comment]
+1

**Comment by axelaris** [comment]
LGTM

**Comment by axelaris** [comment]
Thank you @mymasse !

**Pull request merged**
