### PR TITLE
Switch to kibana-cf_authentication submodule

### PR DESCRIPTION
**Pull request by Infra-Red**
Hi @axelaris !
This PR will replace current kibana-cf_authentication. I set kibana-cf_authentication to submodule from 18F team. In this fork done a lot of the necessary changes for implementing Kibana and UAA integration.
Thanks!

### CODE REVIEW

**Comment by axelaris** [comment]
We've tried to reach out @LinuxBozo to have a direct PR there.
Since we got no answer, we're going to attach his original PR as a reference.

**Comment by LinuxBozo** [comment]
@Infra-Red @axelaris Apologies for not getting back in touch sooner, been tied up with other priorities, both work and home. Would love to have the community take ownership of this, so if you all are still game to have a PR done, I'll carve out some time to do it. Just let me know..

**Comment by axelaris** [comment]
Hi @LinuxBozo, nice to hear that!
Should I revert last merge then?

**Comment by LinuxBozo** [comment]
@axelaris Sure thing. If you do that, I'll carve out some time this weekend to get in the PR.

**Comment by axelaris** [comment]
@LinuxBozo done!
Thank you for help.

**Pull request merged**
