### PR TITLE
Type fix

### PR DESCRIPTION
**Pull request by hannayurkevich**
Filters config https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/src/logstash-filters/default.conf.erb removes the `@type` field:
`mutate {`
`rename => { "[tags]" => "[@tags]" }`
`remove_field => [ "@version" ]`
**`remove_field => "@type"`**
`}`

This leads to 'unknown' `@type` because `filters_post.conf` sets it to 'unknown' if it hasn't been set in logstash filters:
`if ![@type] {`
 `     mutate {`
 `       add_field => [ "@type", "unknown" ]`
`      }`
`    }`
(see https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/parser/templates/config/filters_post.conf.erb).

Additionally config https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/parser/templates/config/input_and_output.conf.erb sets 
document_type to `"<%= p('logstash_parser.elasticsearch_index_type') %>"` which is set to `"%{@type}"` by default (see https://github.com/logsearch/logsearch-boshrelease/blob/develop/jobs/parser/spec). So the field is used and should be set correctly.

So we shouldn't remove `@type` field in `filters_override`. Instead we need to replace it with `[@metadata][type]` value.

### CODE REVIEW

**Comment by cromega** [comment]
@hannayurkevich: thanks for pointing this one out, we are discussing the rules in default.conf.erb. The solution to this problem may be slightly different from what you suggest in this PR.

**Comment by hannayurkevich** [comment]
@cromega: Ok, thanks for letting me know. Looking forward to the problem fix )

**Comment by cromega** [comment]
@hannayurkevich: as an attempt to get the tests up to speed with recent logsearch-boshrelease changes I got rid of the `remove_field => "@type"` line as it does not play well with the rest of the filters as you have pointed it out. Does it solve your problem?

**Comment by hannayurkevich** [comment]
@cromega: Thank you, it is better than nothing :) But in fact "not removing `@type`" is not enough. We should get `@type` be set to different values for different logs (`uaa`, `vcap`, etc.).

In your [commit ](https://github.com/logsearch/logsearch-for-cloudfoundry/commit/5bfe98d6b29eccba708ae8d29dba47b7f6368181) you made this change for `vcap` logs:
replaced line `replace => { "[@metadata][type]" => "%{[@metadata][type]}_cf" }`
with line `replace => { "@type" => "%{@type}_cf" }`.

But we still keep `[@metadata][type]` in rest filters (see [snippets](https://github.com/logsearch/logsearch-for-cloudfoundry/tree/master/src/logsearch-config/src/logstash-filters/snippets)) and do not set `@type` in them.

I think it makes sense to keep only one field `@type` and use it instead of `[@metadata][type]`.  Because keeping both of them is really confusing and can lead to future issues.

So to keep `@type` field and do not use `[@metadata][type]` we need to do two more changes:

1.
Do similar replacements (like you did for `vcap`) in other [snippets](https://github.com/logsearch/logsearch-for-cloudfoundry/tree/master/src/logsearch-config/src/logstash-filters/snippets). Because currently each of them sets `[@metadata][type]` to specific values:

firehose.conf: `replace => { "[@metadata][type]" => "%{[event_type]}" }`
app_event.conf: `replace => { "[@metadata][type]" => "app_event" }`
metrics_collector.conf: `replace => { "[@metadata][type]" => "metric" }`
uaa.conf: `replace => { "[@metadata][type]" => "uaa-audit" }`

So we need to change these configs and set `@type` instead of `[@metadata][type]`.

2.
Do not use`[@metadata][type]` in [default.conf](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/master/src/logsearch-config/src/logstash-filters/default.conf.erb), use `@type` instead.

**Comment by hannayurkevich** [comment]
@cromega: Hi! Are planing to do some fixes for @type and [@metadata][type]?

**Pull request closed without merging**
