### PR TITLE
Updates the precision of response_time_ms

### PR DESCRIPTION
**Pull request by aleej**
3 decimal places for app-logmessage-rtr

### CODE REVIEW

**Comment by hannayurkevich** [comment]
@bonzofenix, The change looks good. But some integration tests fail. Please fix them, so that I can merge the PR.

Thank you!

**Comment by bonzofenix** [comment]
@hannayurkevich done!

@aleej & @bonzofenix

**Comment by aleej** [comment]
@hannayurkevich we both signed the CLA and the check is still not green :(

**Review by Infra-Red — APPROVED** [review]
lgtm

**Comment by hannayurkevich** [comment]
Thanks!

**Pull request merged**
